flowchart TD
    begin --> a[The forest is dark and cool.]
    a --> b[Something glints in the undergrowth.]
    b --> c(Investigate.)
    b --> d(Keep walking.)
    c -->|+foundCoin| e[You find a coin. Lucky!]
    d --> f[You emerge on the other side, safe and sound.]
    e --> f
